controller_list:
  - name: arm1_controller
    action_ns:  follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  
  - name: gripper_controller
    action_ns:  follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - f_joint1
    - f_joint2