arm1_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6

gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
  - f_joint1
  - f_joint2
    